# fly.toml app configuration file generated for story-weaver on 2026-07-30T20:34:14+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'story-weaver'
primary_region = 'sin'

[build]
  dockerfile = 'Dockerfile'

[env]
  DEEPSEEK_BASE_URL = 'https://api.deepseek.com'
  PYTHON_VERSION = '3.11'

[[mounts]]
  source = 'checkpoints'
  destination = '/app/generative_agents/results'

[http_service]
  internal_port = 5001
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true

[[services]]
  protocol = ''
  internal_port = 0

  [[services.ports]]
    port = 5001
    handlers = ['http']

[[vm]]
  memory = '2gb'
  cpus = 1
  memory_mb = 2048

[[statics]]
  guest_path = '/app/generative_agents/frontend/static'
  url_prefix = '/static'
